spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      batchSize: 3

#===============================================
# Application specific properties
#===============================================
application:
  server:
    port: 9090
  kafka:
    topic: logging