version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2181"]
      interval: 30s
      timeout: 20s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
       - "9092:9092"
    networks:
      - kafka
    depends_on:
      - zookeeper

#  cassandra:
#    image: cassandra:latest
#    ports:
#      - "9042:9042"

networks:
  kafka:
