spring:
  application:
    name: thrift-server
  kafka:
    consumer.group-id: logging-event
    bootstrap-servers: kafka:9092
  main:
    web-environment: false

info:
  project:
    version: #project.version#

#===============================================
# Application specific properties
#===============================================
application:
  server:
    port: 9090
  kafka:
    topic: logging