spring:
  application:
    name: thrift-server
  main:
    web-environment: false

info:
  project:
    version: #project.version#

#===============================================
# Application specific properties
#===============================================
application:
  server:
    port: 9090