info:
  project:
    version: #project.version#

spring:
  application:
    name: thrift-server
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      batchSize: 3
  main:
    web-environment: false
  profiles:
    active: dev

#===============================================
# Application specific properties
#===============================================
application:
  server:
    port: 9090
